- src/usr/bin/diffuse
python3 popen streams return byte-strings that needs to be decoded into strings
This seems to fix issue #26
> Fix diffuse VCS-integration functionality

- src/usr/bin/diffuse
Traceback (most recent call last):
File "/usr/bin/diffuse", line 5592, in im_retrieve_surrounding_cb
im.set_surrounding(s, len(s), n)
TypeError: Must be string, not bytes
> Fix incorrect conversion.

- CHANGELOG.md
- src/usr/bin/diffuse
Alternative to the fix proposed @rkroetch (#51) about a bug he found. I think this fix is a bit better since `safeRelativePath` is used at several places.
I am unsure it won't break something else, but since the main difference between Python 2 and 3 is that UTF-8 is the default text format, I assume `codecs.encode` is not useful any more.
> Fix error when using '-m' in an SVN repo

- README.md
- com.github.mightycreak.Diffuse.yml
Will eventually fix #65
This is an experiment to deploy Diffuse using Flatpak.
To install Diffuse locally:
flatpak-builder builddir-flatpak --user --install com.github.mightycreak.Diffuse.yml
To run Diffuse through Flatpak:
flatpak run com.github.mightycreak.Diffuse
To uninstall Diffuse:
flatpak remove com.github.mightycreak.Diffuse
> Add Flatpak config file

- CHANGELOG.md
This will simplify a bit the release process, and GitHub has a simple
way to see the diff between two releases anyway.
> Remove the release links in CHANGELOG.md

- src/diffuse/utils.py
Fixes #137
No idea if this reintroduces a lint error that 812ca1779f9537153d57fd89a08c6957361d93ac tried to solve -- we'll see.
> Fix SyntaxError in utils.py

- CHANGELOG.md
I did change the place where the linters were executed, but then I
found a better solution and linters are called on the source files
directly.
> Remove a line in CHANGELOG.md

- CHANGELOG.md
- src/diffuse/preferences.py
`get_text` was not defined on all the widgets
* Use `get_text` when available in widget
* Use `get_font` when widget is a `Gtk.FontButton`
* Raise TypeError exception otherwise
Fixes #156
> Fix preferences crash

- CHANGELOG.md
- docs/developers/developers-setup.md
from developer instructions.
- Safer
- Plain `pip` might be unavailable.
> Refer to pip3

- CHANGELOG.md
- data/io.github.mightycreak.Diffuse.appdata.xml.in
- src/diffuse/dialogs.py
- src/diffuse/main.py
- src/diffuse/utils.py
This PR is based on #93, but I couldn't push on top of it so I had to create a new PR.
In this PR:
* Create only one dialog even if multiple files has been changed on disk
* fix: the calls to `NumericDialog` weren't working
* use `transient_for` instead of `parent` when creating new `Gtk.Dialog`
* Changelog: I removed the "thanks to" (just kept the mentions to the users), because it felt weird to put "thanks to myself" :sweat_smile: 
Fixes #16
> Prompt once to reload if more than one file modified externally (bis)

- docs/developers/developers-setup.md
At least not on my machine.
Includes a change to make the `build/` directory very explicit.
> Don't need root on macOS

- data/io.github.mightycreak.Diffuse.appdata.xml.in
There is a recursive dependency between the repo and the `appstream-util` tool.
This doesn't fix it entirely, but at least we don't need to reprocess the CI twice because the GitHub Pages action isn't finished yet and the images aren't published to the website.
> fix: reference the images from the repo directly

- CHANGELOG.md
- src/diffuse/window.py
Fixes #188 
It was related to the GTK action names. Only the action names defined in the `menu` bindings are used with `Gio.Action.print_detailed_name` which doesn't tolerate `_` in the action name. This is a quick fix (of a quick fix :sweat_smile: ) and this time it properly formats the action name as GTK would expect it.
> fix: quick fix for the GTK accelerators

- CHANGELOG.md
- data/usr/share/gnome/help/diffuse/C/diffuse.xml
- data/usr/share/gnome/help/diffuse/cs/diffuse.xml
- data/usr/share/gnome/help/diffuse/it/diffuse.xml
- data/usr/share/gnome/help/diffuse/ru/diffuse.xml
- src/diffuse/resources.py
- src/diffuse/widgets.py
- src/diffuse/window.py
Fix a couple of issues:
* Renamed all the action names to get rid of the quick fix that was replacing `_` by `-` at runtime
* Some signals weren't properly renamed from the previous GTK3 migration
* Fixed the syntax menu that wasn't working anymore
> Proper fix for accelerators

- src/diffuse/main.py
`DiffuseApplication.on_shutdown()` is called even in command line mode (as expected), but when running diffuse with the argument `--version`, the member `self.statepath` is not initialized.
The fix simply tests if the variable has been initialized (not an empty string).
> fix: error when runnin with arg --version

- CHANGELOG.md
- src/diffuse/resources.py
Remove use of `distutils` which has been removed from Python 3.12 (see:
https://docs.python.org/3/whatsnew/3.12.html#summary-release-highlights)
Fixes #215
> fix: fix compatibility with Python 3.12

- .github/workflows/ci.yml
- CHANGELOG.md
- data/io.github.mightycreak.Diffuse.appdata.xml.in
- docs/translators.md
- po/tr.po
- Add vcs-browser and translate URLs
- Add the translation tag
- Mark the developer name and release descriptions as untranslatable
- Remove redundant paragraph from the translation document
> Appdata and translation related patches

- data/io.github.mightycreak.Diffuse.appdata.xml.in
It appears that the appstream project no longer supports
`translatable=no` properties, and gettext extract them as translatable.
I opened an issue to inform about the situation, but `translatable=no`
properties are not accepted by developers. You can find the issue
here: `https://github.com/ximion/appstream/issues/623
**Please test your script or string extraction process before merging this PR.**
> In MetaInfo files, each individual paragraph of a description
> (or enumerated entry) is translated individually, however,
> you can only exclude the complete block from being translated
> by adding `translate="no"` to the description element.
Source: https://freedesktop.org/software/appstream/docs/sect-Quickstart-Translation.html
Flathub requires a developer tag and developer ID. Also …
> Appdata related patches

- CHANGELOG.md
- docs/developers/developers-setup.md
Use `uname -m` (machine, e.g. "x86_64") instead of `uname -p` (processor).
> docs: fix incorrect flatpak command to install runtime SDK

- .github/workflows/ci.yml
- CHANGELOG.md
- docs/developers/developers-setup.md
* Updated Python to 3.9 (3.8 reached end of life)
* Updated Flatpak container image (as written in https://github.com/marketplace/actions/flatpak-builder)
> chore(cicd): update GitHub actions
